### ISSUE TITLE
Provide ability to specify which detection in a track is the exemplar

### ISSUE THREAD

**Issue by clnowacki** [openmpf/openmpf#1558] opened 2022-07-29 16:38 UTC
For a given track, the workflow manager currently chooses the detection with the highest confidence as the exemplar for the track. For some components, this may not be the best choice. For example, when all of the detections in the track have the same confidence, the workflow manager will choose the first detection in the track, but it might be more useful to the user of the detection that is the middle of the track were chosen. This task is to allow the selection of the exemplar to be configurable, so that the middle detection in a track can be returned instead of the one with the highest confidence.

**Comment by jrobble** [comment] 2022-08-17 15:58
Duplicate of https://github.com/openmpf/openmpf/issues/1527.

**Closed by jrobble** 2022-08-17 15:58 UTC
Labels: enhancement
